### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Aimee555** [XiaoqiWang/VIPNet#1]
Pardon, when will the code be released?

**Comment by XiaoqiWang** [comment]
Apologies for the delay in updating the code due to health reasons. We'll release it in about a week. Thank you for your understanding.

**Comment by Aimee555** [comment]
Thank you very much


| |
eternity202202
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 7/23/2023 10:24 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [XiaoqiWang/VIPNet] Code (Issue #1) |

Apologies for the delay in updating the code due to health reasons. We'll release it in about a week. Thank you for your understanding.

**Comment by XiaoqiWang** [comment]
Thank you for your interest in our work. We would like to inform you that the code and model have been released, and the issue is now closed.
